#Setting the logging levels for the service
logging:
  level:
    com.netflix: WARN
    org.springframework.web: DEBUG
    com.thoughtmechanix: DEBUG

server:
   port: 8901
   contextPath: /auth
   
spring:
   application:
      name: cloud-auth-service
   datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/emarket?useUnicode=true&characterEncoding=utf-8
      username: root
      password: admin
   jpa:
      hibernate:
         database-platform: org.hibernate.dialect.MySQLDialect
         ddl-auto: update
         show-sql: true
         
eureka:
   instance:
      preferIpAddress: true		
      client: 
         registerWithEureka: true	
         fetchRegistry: true		
         serviceUrl: 
            defaultZone: http://localhost:8761/eureka/